# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582356caffee9d27a25a018f2a30c19cf05f6cf6cacb80d6a5a666635327476eb6ee38e655ab5bbcb79791f525b1d3c947f384ea4d6e567535f982e0ef3d757e

test:
  secret_key_base: 6648338e96b1b92929bb3b3589f60d05c89f3e9248ca1b789973b9f246a06ac6660f9df8e4363ab55ca92ce1310c8d02a607c719c4be6573bc56590655319c50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
